FGAbirintos/config/routes.rb
Rails.application.routes.draw do
  get 'forum/index'
  resources :mazes
  resources :commentaries
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

FGAbirintos/app/controllers/mazes_controller.rb
class MazesController < ApplicationController
  before_action :set_maze, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /mazes
  # GET /mazes.json
  def index
    @mazes = current_user.mazes.paginate(:page=>params[:page],:per_page=>8)
  end

  # GET /mazes/1
  # GET /mazes/1.json
  def show
  end

  # GET /mazes/new
  def new
    @maze = Maze.new
  end

  # GET /mazes/1/edit
  def edit
  end

  # POST /mazes
  # POST /mazes.json
  def create
    @maze = current_user.mazes.new(maze_params)
    generateMaze
    respond_to do |format|
      if @maze.save
        format.html { redirect_to @maze, notice: 'Labirinto criado com sucesso.' }
        format.json { render :show, status: :created, location: @maze }
      else
        format.html { render :new }
        format.json { render json: @maze.errors, status: :unprocessable_entity }
      end
    end
    #respond_to do |format|
    #format.html { redirect_to new_maze_path}
  end

  # PATCH/PUT /mazes/1
  # PATCH/PUT /mazes/1.json
  def update
    respond_to do |format|
      if @maze.update(maze_params)
        format.html { redirect_to @maze, notice: 'Labirinto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @maze }
      else
        format.html { render :edit }
        format.json { render json: @maze.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mazes/1
  # DELETE /mazes/1.json
  def destroy
    @maze.destroy
    respond_to do |format|
      format.html { redirect_to mazes_url, notice: 'Labirinto destruído com sucesso.' }
      format.json { head :no_content }
    end
  end

  def validateMaze
    if @maze.sizeMaze.nil?
      @maze.sizeMaze = 3
    elsif @maze.sizeMaze<3
      @maze.sizeMaze = 3
    elsif @maze.sizeMaze>=78
      @maze.sizeMaze = 78
    end
    if @maze.startingPoint.nil? || @maze.startingPoint.length==0
      @maze.startingPoint = 0
    elsif @maze.startingPoint>=@maze.sizeMaze.to_s || @maze.startingPoint.to_i<0
      @maze.startingPoint = 0
    end
    if @maze.endPoint.nil? || @maze.endPoint.length==0
      @maze.endPoint = @maze.sizeMaze-1

    elsif @maze.endPoint>=@maze.sizeMaze.to_s || @maze.endPoint.to_i<0
      @maze.endPoint = @maze.sizeMaze-1
    end
  end

  def arraysToString
    #____________________________________________
    @maze.adjacencyList = ""
    @maze.solutionMaze = ""
    i = 0
    until i==@maze.sizeMaze
      @maze.adjacencyList+=@generatedMaze[i].join(",")
      @maze.solutionMaze+=@answerMaze[i].join(",")
      if i!= @maze.sizeMaze-1
          @maze.adjacencyList+=","
          @maze.solutionMaze+=","
      end
      i+=1
    end
    #____________________________________________
  end

  def checkNeighbour(x,y)
    dx = [0,1,0,-1]
  	dy = [1,0,-1,0]
    numberNeighbour1 = 0
    a = 0
    while a<4
      if indexOutOfBound(x+dx[a],y+dy[a])
        a+=1
        next
      end
      if @generatedMaze[x+dx[a]][y+dy[a]] == 1
  			numberNeighbour1 +=1
      end
      a+=1
    end
    return numberNeighbour1==1
  end
  def indexOutOfBound(x,y,xf=@maze.sizeMaze,go_down=true)
    if go_down
      if x<0 || x>=@maze.sizeMaze || y<0 || y>=@maze.sizeMaze || x>xf
        return true
      end
      return false
    else
      if x<0 || x>=@maze.sizeMaze || y<0 || y>=@maze.sizeMaze || x<xf
        return true
      end
      return false
    end
  end

  def generateSolutionMaze # Xpartida = 0 Xchegada = @maze.sizeMaze-1
    xi = @maze.startingPoint.to_i
    yi = 0
    xf = @maze.endPoint.to_i
    yf = @maze.sizeMaze-1
    @answerPath = []
    @answerMaze[xi][yi] = 1
    @generatedMaze[xi][yi] = 1
    go_down = false
    #Set de Variaveis ____________________________________
    if xi < xf #entao tenho que descer
      go_down = true
    end

    while xi!=xf || yi!=yf
      coin = rand()
      if go_down && coin>=0.5
        if !indexOutOfBound(xi+1,yi,xf,go_down)
          xi += 1
        end
      elsif !go_down && coin>=0.5
        if !indexOutOfBound(xi-1,yi,xf,go_down)
          xi-=1
        end
      else#ir Direita
        if !indexOutOfBound(xi,yi+1,xf,go_down)
          yi+=1
        end
      end
      @answerMaze[xi][yi] = 1
      @generatedMaze[xi][yi] = 1
    end
  end

  def generateMaze
    validateMaze
    # ------ Gerador do labirinto Com 0
    i = 0
    @generatedMaze = []
    @answerMaze = []
    until i==@maze.sizeMaze
      j = 0
      @generatedMaze.push([])
      @answerMaze.push([])
      until j==@maze.sizeMaze
        @generatedMaze[i].push(0)
        @answerMaze[i].push(0)
        j+=1
      end
      i+=1
    end
    generateSolutionMaze
    #____________________________________________
    i = 0
    j = 0
    while i<@maze.sizeMaze
      j=0
      while j<@maze.sizeMaze
        if checkNeighbour(i,j) &&@generatedMaze[i][j] == 0
          @generatedMaze[i][j] = 1
          i -= 2# Faz i = i - 2 pois logo a baixo tem um i++, no fim das contas ele volta uma linha
          break
        end
        j+=1
      end
      i+=1
    end

    #____________________________________ Preencher Labirinto
    arraysToString
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maze
      @maze = Maze.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maze_params
      params.require(:maze).permit(:adjacencyList, :solutionMaze, :startingPoint, :endPoint, :sizeMaze)
    end
end

FGAbirintos/app/helpers/mazes_helper.rb
module MazesHelper
end

FGAbirintos/app/views/mazes/_form.html.erb
<%= form_for @maze, :html => { :class => "form-horizontal maze" } do |f| %>

  <% if @maze.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@maze.errors.count, "error") %> prohibited this maze from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @maze.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :startingPoint, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :startingPoint, :class => 'form-control' %>
    </div>
    <%=f.error_span(:startingPoint) %>
  </div>
  <div class="form-group">
    <%= f.label :endPoint, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :endPoint, :class => 'form-control' %>
    </div>
    <%=f.error_span(:endPoint) %>
  </div>
  <div class="form-group">
    <%= f.label :sizeMaze, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sizeMaze, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sizeMaze) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                mazes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

FGAbirintos/app/views/mazes/edit.html.erb
<%- model_class = Maze -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

FGAbirintos/app/views/mazes/index.html.erb
<%- model_class = Maze -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:startingPoint) %></th>
      <th><%= model_class.human_attribute_name(:endPoint) %></th>
      <th><%= model_class.human_attribute_name(:sizeMaze) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @mazes.each do |maze| %>
      <tr>
        <td><%= maze.startingPoint %></td>
        <td><%= maze.endPoint %></td>
        <td><%= maze.sizeMaze %></td>
        <td><%=l maze.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      maze_path(maze), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      maze_path(maze),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br><%=will_paginate @mazes%>

FGAbirintos/app/views/mazes/new.html.erb
<%- model_class = Maze -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

FGAbirintos/app/views/mazes/show.html.erb
<%- model_class = Maze -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<style>
div.a {
        text-align: center;
}
</style>

<div class="a">
  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:adjacencyList) %>:</strong></dt>
    <dd><% maze =  @maze.adjacencyList %></dd>
    <br>
    <% maze = maze.split(",") %>
    <% i = 0 %>
    <% until i==@maze.sizeMaze %>
      <% j = 0 %>
      <% until j==@maze.sizeMaze %>
        <%= maze[i*@maze.sizeMaze+j]+" " %>
        <% j+=1 %>
      <% end %>
      <br>
      <% i+=1 %>
    <% end %>
    <hr>
    <br>
    <dt><strong><%= model_class.human_attribute_name(:solutionMaze) %>:</strong></dt>
    <dd><%maze = @maze.solutionMaze %></dd>
    <br>
    <% maze = maze.split(",") %>
    <% i = 0 %>
    <% until i==@maze.sizeMaze %>
      <% j = 0 %>
      <% until j==@maze.sizeMaze %>
        <%= maze[i*@maze.sizeMaze+j]+" " %>
        <% j+=1 %>
      <% end %>
      <br>
      <% i+=1 %>
    <% end %>
  </div>
  <hr>
  <br>
  <dt><strong><%= model_class.human_attribute_name(:startingPoint) %>:</strong></dt>
  <dd><%= @maze.startingPoint %></dd>
  <br>
  <dt><strong><%= model_class.human_attribute_name(:endPoint) %>:</strong></dt>
  <dd><%= @maze.endPoint %></dd>
  <br>
  <dt><strong><%= model_class.human_attribute_name(:sizeMaze) %>:</strong></dt>
  <dd><%= @maze.sizeMaze %></dd>
  <br>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              mazes_path, :class => 'btn btn-default'  %>

<% comments = @maze.commentaries %>
<% if !comments.empty? %>
  <hr>
  <h3>Comentários</h3>
  <hr>
  <% comments.each do |item| %>
      <dt><strong><%= item.user.email %>:</strong></dt>
      <%= text_field_tag :comment, item.comment, size:80 %>
    <hr>
  <% end %>
<% end %>

<%= link_to "Novo Comentário", new_commentary_path(:maze_id => @maze.id), :class => 'btn btn-default'  %>