FGAbirintos/config/routes.rb
Rails.application.routes.draw do
  get 'forum/index'
  resources :mazes
  resources :commentaries
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

FGAbirintos/app/models/commentary.rb
class Commentary < ApplicationRecord
    belongs_to :maze
    belongs_to :user
end

FGAbirintos/app/controllers/commentaries_controller.rb
class CommentariesController < ApplicationController
  before_action :set_commentary, only: [:show, :edit, :update, :destroy]

  # GET /commentaries
  # GET /commentaries.json
  def index
    @commentaries = current_user.commentaries
  end

  # GET /commentaries/1
  # GET /commentaries/1.json
  def shows
  end

  # GET /commentaries/new
  def new
    @commentary = Commentary.new
    @maze = Maze.new
    @maze.id = params[:maze_id]
  end

  # GET /commentaries/1/edit
  def edit
  end

  # POST /commentaries
  # POST /commentaries.json
  def create
    @commentary = Commentary.new(commentary_params)
    @commentary.user = current_user

    respond_to do |format|
      if @commentary.save
        format.html { redirect_to @commentary.maze, notice: 'Comentario criado com sucesso.' }
        format.json { render :show, status: :created, location: @commentary }
      else
        format.html { render :new }
        format.json { render json: @commentary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commentaries/1
  # PATCH/PUT /commentaries/1.json
  def update
    respond_to do |format|
      if @commentary.update(commentary_params)
        format.html { redirect_to @commentary, notice: 'Comentario atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @commentary }
      else
        format.html { render :edit }
        format.json { render json: @commentary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commentaries/1
  # DELETE /commentaries/1.json
  def destroy
    @commentary.destroy
    respond_to do |format|
      format.html { redirect_to commentaries_url, notice: 'Comentario destruído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commentary
      @commentary = Commentary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commentary_params
      params.require(:commentary).permit(:comment, :maze_id)
    end
end

FGAbirintos/app/helpers/commentaries_helper.rb
module CommentariesHelper
end

FGAbirintos/app/views/commentaries/_form.html.erb
<%= form_for @commentary, :html => { :class => "form-horizontal commentary" } do |f| %>

  <% if @commentary.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@commentary.errors.count, "error") %> prohibited this commentary from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @commentary.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :comment, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :comment, :class => 'form-control' %>
    </div>
    <%=f.error_span(:comment) %>
  </div>

  <%= f.hidden_field :maze_id, :value => @maze.id %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                forum_index_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

FGAbirintos/app/views/commentaries/edit.html.erb
<%- model_class = Commentary -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

FGAbirintos/app/views/commentaries/index.html.erb
<%- model_class = Commentary -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%= model_class.human_attribute_name(:maze_id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @commentaries.each do |commentary| %>
      <tr>
        <td><%= link_to commentary.id, commentary_path(commentary) %></td>
        <td><%= commentary.comment %></td>
        <td><%= commentary.maze_id %></td>
        <td><%= commentary.user_id %></td>
        <td><%=l commentary.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      commentary_path(commentary), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_commentary_path(commentary), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      commentary_path(commentary),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_commentary_path,
            :class => 'btn btn-primary' %>

FGAbirintos/app/views/commentaries/new.html.erb
<%- model_class = Commentary -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

FGAbirintos/app/views/commentaries/show.html.erb
<%- model_class = Commentary -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @commentary.comment %></dd>
  <dt><strong><%= model_class.human_attribute_name(:maze_id) %>:</strong></dt>
  <dd><%= @commentary.maze_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @commentary.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              commentaries_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_commentary_path(@commentary), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              commentary_path(@commentary),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>